Файл objects.py и enemies.py не задействованы 